# Generated by Django 5.1.4 on 2025-01-12 14:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monitor',
            new_name='Collected',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='comment',
            field=models.TextField(default='default comment'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='program_name',
            field=models.CharField(default='default program', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='room_name',
            field=models.CharField(default='default room', max_length=255),
        ),
        migrations.CreateModel(
            name='CongestionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_app.location')),
            ],
        ),
    ]
