# Generated by Django 5.1.4 on 2025-01-13 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0002_rename_monitor_collected_remove_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collected',
            name='congestion_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
