# Generated by Django 5.1.7 on 2025-03-10 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0003_alter_collected_congestion_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='congestionlevel',
            name='last_update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='congestionlevel',
            name='reliability',
            field=models.IntegerField(default=404),
        ),
        migrations.AlterField(
            model_name='collected',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='location',
            name='comment',
            field=models.TextField(default='default comment is here!'),
        ),
    ]
