# Generated by Django 5.1.7 on 2025-08-12 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0004_congestionlevel_last_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collected',
            name='congestion_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
