# Generated by Django 5.1.7 on 2025-08-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0005_alter_collected_congestion_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congestionlevel',
            name='reliability',
            field=models.IntegerField(default=0),
        ),
    ]
