# Generated by Django 5.1.7 on 2025-09-02 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0006_alter_congestionlevel_reliability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='comment',
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
