# Generated by Django 5.1.7 on 2025-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0007_remove_location_comment_alter_location_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='floor_local_id',
            field=models.IntegerField(default=100),
        ),
    ]
